export EDITOR="nvim"
export GTK2_RC_FILES="$HOME/.gtkrc-2.0"
export ZDOTDIR="$HOME/.config/zsh"
export GEM_HOME="$(ruby -e 'puts Gem.user_dir')"
export PATH="$PATH:$GEM_HOME/bin"
export XDG_CONFIG_HOME="$HOME/.config"
export BROWSER="qutebrowser"
