return {
    astro = {},
    bashls = {},
    clangd = {},
    jdtls = {},
    cssls = {},
    dockerls = {},
    tsserver = {},
    svelte = {},
    eslint = {
        filetypes = {
            "javascript",
            "javascriptreact",
            "javascript.jsx",
            "typescript",
            "typescriptreact",
            "typescript.tsx",
        },
    },
    html = {},
    pyright = {},
    lua_ls = {},
    yamlls = {},
    tailwindcss = {},
    texlab = {},
    volar = {},
}
