return {
    bashls = {},
    clangd = {},
    jdtls = {},
    cssls = {},
    dockerls = {},
    tsserver = {},
    svelte = {},
    eslint = {},
    html = {},
    pyright = {},
    sumneko_lua = {},
    yamlls = {},
    tailwindcss = {},
}
