#!/usr/bin/env sh

source "$HOME/.config/sketchybar/colors.sh" # Loads all defined colors
source "$HOME/.config/sketchybar/icons.sh"  # Loads all defined icons

ITEM_DIR="$HOME/.config/sketchybar/items"
PLUGIN_DIR="$HOME/.config/sketchybar/plugins"

FONT="FiraCode Nerd Font"
# SPACE_CLICK_SCRIPT="yabai -m space --focus \$SID 2>/dev/null" # The script that is run for clicking on space components

PADDINGS=3 # All paddings use this value (icon, label, background)

POPUP_BORDER_WIDTH=2
POPUP_CORNER_RADIUS=11

CORNER_RADIUS=15

SHADOW=on

# General bar and defaults

sketchybar --bar height=30 \
	color=$BAR_COLOR \
	shadow=$SHADOW \
	position=top \
	sticky=on \
	padding_right=0 \
	padding_left=3 \
	corner_radius=$CORNER_RADIUS \
	y_offset=5 \
	margin=5 \
	blur_radius=20 \
	notch_width=200 \
	--default updates=when_shown \
	icon.font="$FONT:Bold:14.0" \
	icon.color=$ICON_COLOR \
	icon.padding_left=$PADDINGS \
	icon.padding_right=$PADDINGS \
	label.font="$FONT:SemiBold:13.0" \
	label.color=$LABEL_COLOR \
	label.padding_left=$PADDINGS \
	label.padding_right=$PADDINGS \
	background.padding_right=$PADDINGS \
	background.padding_left=$PADDINGS \
	popup.background.border_width=2 \
	popup.background.corner_radius=11 \
	popup.background.border_color=$POPUP_BORDER_COLOR \
	popup.background.color=$POPUP_BACKGROUND_COLOR \
	popup.background.shadow.drawing=$SHADOW

# Left
# source "$ITEM_DIR/apple.sh"
source "$ITEM_DIR/spaces.sh"
source "$ITEM_DIR/front_app.sh"

# Center

# Right
source "$ITEM_DIR/clock.sh"
source "$ITEM_DIR/calendar.sh"
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/volume.sh"
# source "$ITEM_DIR/brew.sh"
source "$ITEM_DIR/cpu.sh"
source "$ITEM_DIR/spotify.sh"
# source "$ITEM_DIR/network.sh"

#################### Finalizing Setup ####################

sketchybar --update

echo "sketchybar configuration loaded.."
