#!/usr/bin/env bash

if [ -z "$1" ]
then
    echo "Please give a file to compile and run."
    exit
fi

filename="$1"

filename="${filename%.*}"


flag="-std=c++17 -Wall -Wextra -Wshadow -Wconversion -Wfloat-equal"

dbgFlag="-fsanitize=address -fsanitize=undefined -fsanitize=float-divide-by-zero -fsanitize=float-cast-overflow -fno-sanitize-recover=all -fstack-protector-all"

echo $2

if [ "$2" == "-d" ]
then
    printf "g++ $1 -o $filename $flag $dbgFlag"

    printf "\n\nCompiled with DEBUG flags enabled, code may be slower than normal"
    printf "\n|---- \e[0;34mCompilation output\e[m ----|\n\n"

    g++ $1 -o $filename $flag $dbgFlag
else
    printf "g++ $1 -o $filename $flag"

    printf "\n\n|---- \e[0;34mCompilation output\e[m ----|\n\n"

    g++ $1 -o $filename $flag
fi



printf "\n|---- \e[0;34mRunning\e[m ----|\n\n"

# replace gtime with time on linux operating systems
gtime -f '\n|--------|\n\n  real\t%E\n  user\t%U\n  sys\t%S\n  mem\t%MKB\n' ./$filename
