#!/bin/bash

echo -n "What is the name: "
read name
echo -n "How many files do you need (less then 27): "
read numfiles
echo -n "How long does your template need to be (minimal, short, long, usaco-training): "
read len
if (($len != "minimal" && $len != "short" && $len != "long" && $len != "usaco-training")) 
then
    echo "Your desired template is unavailable. Please check if you typed it correctly"
elif ((numfiles > 26))
then
    echo "Can't create more than 26 files, please choose a lower number"
else
    echo "Creating Directory..."
    mkdir "$PWD/$name"
    cd "$PWD/$name"
    echo "Created Directory!"
    echo "Creating files..."
    abc="abcdefghijklmnopqrstuvwxyz"
    for ((i = 0; i < numfiles; i++)) do
        cp "$HOME/cp/Implementations/template_$len.cpp" "$PWD/${abc:$i:1}.cpp"
        echo "Copied to ${abc:$i:1}.cpp"
    done
fi

echo "Done!"
