#!/usr/bin/env python3

import sys
from tqdm import tqdm

import pdf2image
import pymupdf
from ocrmac import ocrmac


def fit_bbox(text, width):
    for i in range(1, 100):
        trial_width = pymupdf.get_text_length(text, fontsize=i)

        if trial_width > width:
            return i - 1

    return 1


pdf_loc = sys.argv[1]
pdf_save_loc = sys.argv[2]

pdf = pymupdf.open(pdf_loc)

new_pdf = pymupdf.Document()

for i in range(len(pdf)):
    print("Page:", i)
    page = pdf[i]
    page_width = page.rect.width
    page_height = page.rect.height

    # convert pdf to png
    pngImage = pdf2image.convert_from_path(
        pdf_loc, dpi=500, first_page=i + 1, last_page=i + 1
    )[0]

    # get ocr
    annotations = ocrmac.OCR(
        pngImage, language_preference=["en-US"], framework="vision"
    ).recognize()

    print("Annotations:", annotations)
    print(page_width, page_height)

    # create ocr layer
    print("Adding ocr to document")
    for text, confidence, bbox in tqdm(annotations):
        x, y, w, h = bbox

        x0 = x * page_width
        y0 = (1 - y - h) * page_height
        x1 = (x + w) * page_width
        y1 = (1 - y) * page_height

        # print("{0:.2f} {1:.2f} {2:.2f} {3:.2f}".format(x0, y0, x1, y1))

        rect = pymupdf.Rect(x0, y0, x1, y1)
        point = pymupdf.Point(x0, y1)

        font_size = fit_bbox(text, rect.width)

        page.insert_text(point, text, fontsize=font_size, render_mode=3, overlay=True)

    print("Added ocr to document")


pdf.save(pdf_save_loc)
