#!/usr/bin/env bash

if [ -z "$1" ]; then
    echo "Please give a file to compile and run."
    exit
fi

filename="$1"

filename="${filename%.*}"

printf "|--------|\n\n"

# replace gtime with time on linux operating systems
gtime -f '\n|--------|\n\n  real\t%E\n  user\t%U\n  sys\t%S\n  mem\t%MKB\n' ./$filename
