#!/usr/bin/env bash

# modified from theprimeagen

search_dirs="~/.dotfiles ~/programming ~ ~/.config ~/Bao/ ~/Bao/2 Projects/"
exclude_dirs=""

if [[ $# -eq 1 ]]; then
	selected=$1
else
	# selected=$(find "$search_dirs" -mindepth 0 -maxdepth 3 -type d | sort | uniq | fzf)
	selected=$(find ~/.dotfiles ~/programming ~ ~/.config ~/Bao/2\ Projects -mindepth 0 -maxdepth 2 -type d | sort | uniq | fzf)
fi

if [[ -z "$selected" ]]; then
	exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
	tmux new-session -s "$selected_name" -c "$selected"
	exit 0
fi

if ! tmux has-session -t="$selected_name" 2>/dev/null; then
	tmux new-session -ds "$selected_name" -c "$selected"
fi

tmux new-session -A -s "$selected_name" -c "$selected" || tmux switch -t "$selected_name" || tmux switch-client -t "$selected_name"
