#!/usr/bin/env bash

brew upgrade
# echo "$(whoami) ALL=(root) NOPASSWD: sha256:$(shasum -a 256 $(which yabai) | cut -d " " -f 1) $(which yabai) --load-sa"

# spicetify upgrade
# spicetify restore apply
