#!/usr/bin/env bash

vol=`pulseaudio-ctl full-status | awk '{print $1}'`
mute=`pulseaudio-ctl full-status | awk '{print $2}'`

# stngth=`pulseaudio-ctl | awk -F '=' '/Volume level/ {print $4}' | cut -d '/' -f 1`
bars=`expr $vol / 10`

case $bars in
  0)  bar='[----------]' ;;
  1)  bar='[/---------]' ;;
  2)  bar='[//--------]' ;;
  3)  bar='[///-------]' ;;
  4)  bar='[////------]' ;;
  5)  bar='[/////-----]' ;;
  6)  bar='[//////----]' ;;
  7)  bar='[///////---]' ;;
  8)  bar='[////////--]' ;;
  9)  bar='[/////////-]' ;;
  10) bar='[//////////]' ;;
  *)  bar='[----!!----]' ;;
esac

if [[ $mute == 'yes' ]];
then
    bar='[----XX----]'
fi

echo $bar
