#!/usr/bin/env sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

yabai -m space 1 --label "1"
yabai -m space 2 --label "2"
yabai -m space 3 --label "3"
yabai -m space 4 --label "4"
yabai -m space 5 --label "5"
yabai -m space 6 --label "6"
yabai -m space 7 --label "7"
yabai -m space 8 --label "8"
yabai -m space 9 --label "9"
# yabai -m space 1 --label "one"
# yabai -m space 2 --label "two"
# yabai -m space 3 --label "three"
# yabai -m space 4 --label "four"
# yabai -m space 5 --label "five"
# yabai -m space 6 --label "six"
# yabai -m space 7 --label "seven"
# yabai -m space 8 --label "eight"
# yabai -m space 9 --label "nine"

# float system preferences. Most of these just diable Yabai form resizing them.
yabai -m rule --add app="^System Preferences$" sticky=on layer=above manage=off
yabai -m rule --add app="Stats" sticky=on layer=above manage=off
yabai -m rule --add app="Calculator" sticky=on layer=above manage=off
yabai -m rule --add app="^Finder$" sticky=on layer=above manage=off
yabai -m rule --add app="^Disk Utility$" sticky=on layer=above manage=off
yabai -m rule --add app="^System Information$" sticky=on layer=above manage=off
yabai -m rule --add app="^Activity Monitor$" sticky=on layer=above manage=off
yabai -m rule --add app="^Path Finder$" manage=off
yabai -m rule --add app="^console$" manage=off
yabai -m rule --add app="^Digital Colou?r Meter$" sticky=on manage=off
yabai -m rule --add app="Pomotroid" manage=off

## Some random global settings
# yabai -m config focus_follows_mouse          autofocus
# yabai -m config focus_follows_mouse          on
# New window spawns to the right if vertical split, or bottom if horizontal split
yabai -m config window_placement second_child
yabai -m config window_topmost off
yabai -m config window_opacity on
yabai -m config window_opacity_duration 0.15
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.95
yabai -m config window_shadow float

yabai -m config window_border on
yabai -m config window_border_width 4
yabai -m config active_window_border_color 0xFFbb9af8
yabai -m config normal_window_border_color 0xFF565f89
yabai -m config insert_feedback_color 0xff414868

## some other settings
yabai -m config auto_balance on
yabai -m config split_ratio 0.50
# # set mouse interaction modifier key (default: fn)
yabai -m config mouse_modifier fn
# set modifier + left-click drag to resize window (default: move)
yabai -m config mouse_action1 move
# set modifier + right-click drag to resize window (default: resize)
yabai -m config mouse_action2 resize

# general space settings
#yabai -m config focused_border_skip_floating  1
#yabai -m config --space 3 layout             float

## Change how yabai looks
yabai -m config layout bsp
yabai -m config top_padding 5
yabai -m config bottom_padding 5
yabai -m config left_padding 5
yabai -m config right_padding 5
yabai -m config window_gap 5

yabai -m config external_bar all:35:0

echo "yabai configuration loaded.."

#END
